### ISSUE TITLE
Move style for portrait and qr code to css file

### ISSUE THREAD

**Issue by veit** [cusyio/jupyter-reveal#5]
1. Add css classes in markdown syntax, e.g.:

    ```markdown
    ![Portrait Frank Hofmann](fho.png# portrait)
    …
    ![QR-Code](qrcode_enterpy-dvc.svg# qrcode)
    ```
2. Add styles to css file:

    ```css
    img[src~="portrait"] {
        float: left;
        width: 256px;
        margin-right: 32px;
        border-radius: 50%;}

    img[src~="qrcode"] {
        width: 128px;
        margin: 20px 32px 0 0;}
    ```
